workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

stages:
  - start
  - test

always-run:
  stage: start
  script: 
    - echo "Always run"
    - echo $CI_DEFAULT_BRANCH
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_IID
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_URL
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_COMMIT
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_COMMIT_URL


run test: 
    stage: test
    image: node:17-alpine
    script:
      - npm i
      - npm test
